# Generated by Django 5.2.6 on 2025-09-25 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Где выполняется привычка', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Во сколько выполнять', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Что будете делать', max_length=255, verbose_name='Действие')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликована или нет')),
                ('is_pleasent', models.BooleanField(default=False, verbose_name='Приятная привычка?')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='Периодичность (дней)')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлена')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Укажите приятную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_to', to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
    ]
