"""Edit duration, add rating

Revision ID: 5321b9cd793d
Revises: c71aaf90f2a0
Create Date: 2025-12-01 19:31:55.731111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5321b9cd793d'
down_revision: Union[str, Sequence[str], None] = 'c71aaf90f2a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###
