"""Add duration to movies

Revision ID: c71aaf90f2a0
Revises: bcd717f367d7
Create Date: 2025-12-01 19:10:27.939539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71aaf90f2a0'
down_revision: Union[str, Sequence[str], None] = 'bcd717f367d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'duration')
    # ### end Alembic commands ###
